site_name: Prophetverse

theme:
  name: material
  logo: static/logo-removebg.png
repo_url: https://github.com/felipeangelimvieira/prophetverse

nav:
  - Home: README.md
  - Examples:
      - Univariate Time Series: examples/univariate.ipynb
      - Hierarchical Time Series: examples/hierarchical.ipynb
      - Count Time Series: examples/count-data.ipynb
      - Custom Trend: examples/custom-trend.ipynb
  - Reference:
      - Sktime:
        - Prophetverse: reference/sktime/prophetverse.md
        - Prophet: reference/sktime/prophet.md
        - ProphetGamma: reference/sktime/prophet_gamma.md
        - ProphetNegBinomial: reference/sktime/prophet_negbin.md
        - Hierarchical Prophet: reference/sktime/hierarchical_prophet.md
      - Core:
        - Inference Engine: reference/core/inference_engine.md
      - Exogenous Effects: reference/effects.md
  - Development:
    - Contributing to Prophetverse:  development/development-guide.md





plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
  - mkdocs-jupyter:
      use_directory_urls: false

markdown_extensions:
  - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
