[tool.poetry]
name = "prophetverse"
version = "0.3.0"
description = ""
authors = ["Felipe Angelim <felipeangelim@gmail.com>"]
readme = "README.md"
packages = [{ include = "prophetverse", from="src"}]

[tool.poetry.dependencies]
python = ">=3.9, <3.13"
sktime = ">=0.30.0"
numpyro = ">=0.13.2"
optax = ">=0.2"
graphviz = "^0.20.3"


[project.optional-dependencies]
dev = [
    "ipykernel >=6.26.0,<7.0.0",
    "pytest >=8.0.0,<9.0.0",
    "sphinx >=7.2.6,<8.0.0",
    "matplotlib >=3.8.2,<4.0.0",
    "mkdocs >=1.5.3,<2.0.0",
    "mkdocstrings-python >=1.9.0,<2.0.0",
    "mkdocs-jupyter >=0.24.6,<0.25.0",
    "pymdown-extensions >=10.7.1,<11.0.0",
    "mkdocs-material >=9.5.14,<10.0.0",
    "pytest-cov >=5.0.0,<6.0.0",
    "pre-commit >=3.7.1,<4.0.0",
    "commitlint >=1.0.0,<2.0.0",
    "isort >=5.13.2,<6.0.0",
    "black >=24.4.2,<25.0.0",
    "pydocstyle >=6.3.0,<7.0.0",
    "mypy >=1.10.0,<2.0.0",
    "pylint >=3.2.2,<4.0.0",
    "mkdocstrings ^0.25.1"
]

[tool.pytest.ini_options]
markers = [
    "ci: marks tests for Continuous Integration",
    "smoke: marks tests for smoke testing",
    ]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pre-commit]
