name: Pre-Release Workflow

on:
  push:
    branches:
      - develop

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures history is checked out

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Bump pre-release version
        run: |
          poetry version prerelease
          echo "NEW_VERSION=$(poetry version --short)" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit and Tag
        run: |
          git commit -am "Bump version to ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}
          git push
          git push --tags

      - name: Create GitHub Pre-Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: Release ${{ env.NEW_VERSION }}
          draft: false
          prerelease: true
